### PR TITLE
Get ember version from ember-source if there is no ember in bower

### PR DESCRIPTION
**Pull request by josemarluedke**

### CODE REVIEW

**Comment by rwjblue** [comment]
This is great! Thank you!

**Comment by rwjblue** [comment]
I'll release when I'm back at my computer (if not in a few hours ping me back to remind me 😜)...

**Comment by josemarluedke** [comment]
@rwjblue ping for the new version. 😄

**Comment by rwjblue** [comment]
Released as v1.0.2 (thanks for reminding me).

**Pull request merged**
